/* tslint:disable */
// This file is generated
// Do not edit this file

import { Messages } from './messages/index'
export * from './messages/index'

export type ChannelChatwootWebsite = {
  messages: Messages
  message: { "tags": { "messageId": { "title": "messageId", "description": "messageId from Chatwoot" }, "senderType": { "title": "senderType", "description": "senderType from Chatwoot" } } }
  conversation: { "tags": { "conversationId": { "title": "Conversation ID", "description": "Conversation ID from Chatwoot" }, "accountId": { "title": "accountId", "description": "accountId from Chatwoot" } }, "creation": { "enabled": false, "requiredTags": [] } }
}