/* tslint:disable */
// This file is generated
// Do not edit this file
import * as humanHandoff from "./humanHandoff/index";
export * as humanHandoff from "./humanHandoff/index";
import * as newConversationTicket from "./newConversationTicket/index";
export * as newConversationTicket from "./newConversationTicket/index";

export type Actions = {
  humanHandoff: humanHandoff.ActionHumanHandoff;
  newConversationTicket: newConversationTicket.ActionNewConversationTicket;
}
