/* tslint:disable */
// This file is generated
// Do not edit this file
import * as chatwootWebsite from "./chatwootWebsite/index";
export * as chatwootWebsite from "./chatwootWebsite/index";

export type Channels = {
  chatwootWebsite: chatwootWebsite.ChannelChatwootWebsite;
}
