/* tslint:disable */
// This file is generated
// Do not edit this file
import * as input from "./input";
export * as input from "./input";
import * as output from "./output";
export * as output from "./output";

export type ActionNewConversationTicket = {
  input: input.Input;
  output: output.Output;
}
