/* tslint:disable */
// This file is generated
// Do not edit this file
import * as text from "./text";
export * as text from "./text";
import * as image from "./image";
export * as image from "./image";
import * as video from "./video";
export * as video from "./video";
import * as file from "./file";
export * as file from "./file";
import * as card from "./card";
export * as card from "./card";
import * as choice from "./choice";
export * as choice from "./choice";

export type Messages = {
  text: text.Text;
  image: image.Image;
  video: video.Video;
  file: file.File;
  card: card.Card;
  choice: choice.Choice;
}
